export const ERROR_CODES = {
  // ── Auth ─────────────────────────────────────────────────────────────────
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_AUTH_METHOD: 'INVALID_AUTH_METHOD',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  MFA_EXPIRED: 'MFA_EXPIRED',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_REFRESH_FAILED: 'TOKEN_REFRESH_FAILED',

  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  DEVICE_MISMATCH: 'DEVICE_MISMATCH',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_CHANGE_FAILED: 'PASSWORD_CHANGE_FAILED',

  WEBAUTHN_NOT_SUPPORTED: 'WEBAUTHN_NOT_SUPPORTED',
  WEBAUTHN_VERIFICATION_FAILED: 'WEBAUTHN_VERIFICATION_FAILED',
  WEBAUTHN_CHALLENGE_EXPIRED: 'WEBAUTHN_CHALLENGE_EXPIRED',

  RATE_LIMITED: 'RATE_LIMITED',

  // ── Business ─────────────────────────────────────────────────────────────
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
  BUSINESS_ALREADY_EXISTS: 'BUSINESS_ALREADY_EXISTS',
  BUSINESS_ACCESS_DENIED: 'BUSINESS_ACCESS_DENIED',
  BUSINESS_CREATE_FAILED: 'BUSINESS_CREATE_FAILED',
  BUSINESS_UPDATE_FAILED: 'BUSINESS_UPDATE_FAILED',
  BUSINESS_DELETE_FAILED: 'BUSINESS_DELETE_FAILED',

  // ── Finance ──────────────────────────────────────────────────────────────
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_UPDATE_FAILED: 'ASSET_UPDATE_FAILED',
  LIABILITY_NOT_FOUND: 'LIABILITY_NOT_FOUND',
  LIABILITY_UPDATE_FAILED: 'LIABILITY_UPDATE_FAILED',
  CATEGORIZATION_RULE_NOT_FOUND: 'CATEGORIZATION_RULE_NOT_FOUND',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',

  // ── Tax ──────────────────────────────────────────────────────────────────
  TAX_CALCULATION_FAILED: 'TAX_CALCULATION_FAILED',
  TAX_NO_BUSINESS_FOUND: 'TAX_NO_BUSINESS_FOUND',
  TAX_INVALID_YEAR: 'TAX_INVALID_YEAR',

  // ── Dashboard ────────────────────────────────────────────────────────────
  DASHBOARD_INVALID_DATE_RANGE: 'DASHBOARD_INVALID_DATE_RANGE',
  DASHBOARD_FETCH_FAILED: 'DASHBOARD_FETCH_FAILED',

  // ── Mono (Bank Linking) ──────────────────────────────────────────────────
  MONO_ACCOUNT_NOT_FOUND: 'MONO_ACCOUNT_NOT_FOUND',
  MONO_LINK_FAILED: 'MONO_LINK_FAILED',
  MONO_REAUTH_FAILED: 'MONO_REAUTH_FAILED',
  MONO_WEBHOOK_INVALID: 'MONO_WEBHOOK_INVALID',
  MONO_SYNC_FAILED: 'MONO_SYNC_FAILED',
  MONO_NO_LINKED_ACCOUNTS: 'MONO_NO_LINKED_ACCOUNTS',

  // ── Payments ─────────────────────────────────────────────────────────────
  PAYMENT_PLAN_NOT_FOUND: 'PAYMENT_PLAN_NOT_FOUND',
  PAYMENT_PLAN_UPDATE_FAILED: 'PAYMENT_PLAN_UPDATE_FAILED',
  PAYMENT_INIT_FAILED: 'PAYMENT_INIT_FAILED',
  SUBSCRIPTION_ALREADY_ACTIVE: 'SUBSCRIPTION_ALREADY_ACTIVE',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',

  // ── Generic ──────────────────────────────────────────────────────────────
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  PLAN_REQUIRED: 'PLAN_REQUIRED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
