import { ApiProperty } from '@nestjs/swagger';

export class TaxBandBreakdownDto {
  @ApiProperty({
    description: 'Human-readable label for the PIT band applied',
    example: 'Next 2,200,000',
  })
  bandLimit: string;

  @ApiProperty({ description: 'Applied PIT rate for the band', example: '15%' })
  rate: string;

  @ApiProperty({
    description: 'Portion of chargeable income taxed in this band',
    example: 1200000,
  })
  taxableAmount: number;

  @ApiProperty({
    description: 'Tax generated by this band',
    example: 180000,
  })
  taxGenerated: number;
}

export class PitCalculationDto {
  @ApiProperty({
    description: 'Profit remaining after deductions and consolidated relief allowance',
    example: 2600000,
  })
  chargeableIncome: number;

  @ApiProperty({
    description: 'Consolidated relief allowance applied before PIT bands',
    example: 1100000,
  })
  consolidatedReliefAllowance: number;

  @ApiProperty({
    description: 'Estimated annual Personal Income Tax',
    example: 603000,
  })
  estimatedAnnualTax: number;

  @ApiProperty({
    description: 'Monthly amount to reserve for PIT',
    example: 50250,
  })
  estimatedMonthlySetAside: number;

  @ApiProperty({
    description: 'Minimum tax floor used in the estimate',
    example: 100000,
  })
  minimumTaxFloor: number;

  @ApiProperty({
    description: 'Whether the 1% minimum tax floor determined the PIT estimate',
    example: false,
  })
  minimumTaxApplied: boolean;

  @ApiProperty({
    type: [TaxBandBreakdownDto],
    description: 'Progressive PIT band-by-band calculation breakdown',
  })
  breakdown: TaxBandBreakdownDto[];
}

export class CitCalculationDto {
  @ApiProperty({
    description: 'Revenue and asset-based company classification used for CIT',
    example: 'Medium Company',
  })
  companySize: string;

  @ApiProperty({
    description: 'Alias of the company classification for reporting',
    example: 'Medium Company',
  })
  companyCategory: string;

  @ApiProperty({
    description: 'Profit remaining after deductions for CIT estimation',
    example: 4500000,
  })
  assessableProfit: number;

  @ApiProperty({
    description: 'Estimated taxable profit used for the CIT estimate',
    example: 4500000,
  })
  estimatedTaxableProfit: number;

  @ApiProperty({
    description: 'Applied Company Income Tax rate',
    example: '20%',
  })
  taxRateApplied: string;

  @ApiProperty({
    description: 'Estimated annual Company Income Tax',
    example: 900000,
  })
  estimatedAnnualTax: number;

  @ApiProperty({
    description: 'Monthly amount to reserve for CIT',
    example: 75000,
  })
  estimatedMonthlySetAside: number;

  @ApiProperty({
    description: 'Whether the company is exempt from CIT based on the rule set',
    example: false,
  })
  isExempt: boolean;

  @ApiProperty({
    description: 'Asset total considered when classifying the company',
    example: 125000000,
  })
  totalAssetsConsidered: number;
}

export class ProjectionDto {
  @ApiProperty({
    description: 'Number of months elapsed in the current year',
    example: 5,
  })
  monthsElapsed: number;

  @ApiProperty({
    description: 'Annualized net profit projection for the current year',
    example: 7200000,
  })
  projectedAnnualNetProfit: number;
}

export class DeductionsDto {
  @ApiProperty({
    description: 'Total qualifying health insurance deductions found',
    example: 120000,
  })
  healthInsurance: number;

  @ApiProperty({
    description: 'Total life insurance deductions found',
    example: 80000,
  })
  lifeInsurance: number;

  @ApiProperty({ description: 'Total pension deductions found', example: 300000 })
  pension: number;

  @ApiProperty({
    description: 'Total qualifying housing fund deductions found',
    example: 600000,
  })
  housingFund: number;

  @ApiProperty({
    description:
      'Rent expense found in the selected year. This is already included in total expenses and net profit, so it is tracked but not deducted again.',
    example: 900000,
  })
  rent: number;

  @ApiProperty({
    description: 'Additional deductions supplied explicitly by the user',
    example: 50000,
  })
  extra: number;

  @ApiProperty({
    description: 'Sum of built-in and user-supplied deductions',
    example: 1150000,
  })
  total: number;
}

export class TaxEstimateResponseDto {
  @ApiProperty({ description: 'The tax year for the estimate', example: 2025 })
  year: number;

  @ApiProperty({
    description: 'Actual net profit found in transactions for the selected year',
    example: 3000000,
  })
  netProfit: number;

  @ApiProperty({
    description: 'Total revenue for the selected year',
    example: 10000000,
  })
  totalRevenue: number;

  @ApiProperty({
    description: 'Total cost of goods or services already reflected in net profit',
    example: 2500000,
  })
  totalCogs: number;

  @ApiProperty({
    description: 'Total expenses already reflected in net profit',
    example: 4500000,
  })
  totalExpenses: number;

  @ApiProperty({
    description: 'Total non-archived asset value used in the CIT logic',
    example: 125000000,
  })
  totalAssets: number;

  @ApiProperty({
    description: 'Current-year projection metadata, otherwise null',
    required: false,
    nullable: true,
    type: ProjectionDto,
  })
  projection: ProjectionDto | null;

  @ApiProperty({
    description: 'Deduction totals applied to PIT and CIT estimates',
    type: DeductionsDto,
  })
  deductions: DeductionsDto;

  @ApiProperty({
    description: 'Net profit remaining after deductible expenses are applied',
    example: 1850000,
  })
  taxableProfit: number;

  @ApiProperty({
    description: 'Estimated PIT calculation details',
    type: PitCalculationDto,
  })
  pitCalculation: PitCalculationDto;

  @ApiProperty({
    description: 'Estimated CIT calculation details',
    type: CitCalculationDto,
  })
  citCalculation: CitCalculationDto;
}
