import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { In, Repository } from 'typeorm';
import {
  CategorizationRule,
  MatchType,
} from '../../finance/entities/categorization-rule.entity';
import { AccountCategoryType } from '../../finance/entities/account-category.entity';

export const DEFAULT_CATEGORIZATION_RULES: Array<{
  matchType: MatchType;
  matchValue: string;
  category: string;
  subCategory: string;
  priority: number;
}> = [
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'bank charge',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Bank Charges',
    priority: 10,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'bank charges',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Bank Charges',
    priority: 11,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'maintenance fee',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Bank Charges',
    priority: 12,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'card maintenance',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Bank Charges',
    priority: 13,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'account maintenance',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Bank Charges',
    priority: 14,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'charge',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Bank Charges',
    priority: 24,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'commission',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Bank Charges',
    priority: 16,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'sms alert',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Bank Charges',
    priority: 17,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'card maint',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Bank Charges',
    priority: 18,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'stamp duty',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Taxes & Levies',
    priority: 19,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'vat',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Taxes & Levies',
    priority: 20,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'wht',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Taxes & Levies',
    priority: 21,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'withholding tax',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Taxes & Levies',
    priority: 22,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'tax',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Taxes & Levies',
    priority: 23,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'credit interest',
    category: AccountCategoryType.INCOME,
    subCategory: 'Other money inflow',
    priority: 25,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'interest capitalization',
    category: AccountCategoryType.INCOME,
    subCategory: 'Other money inflow',
    priority: 26,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'interest capitalisation',
    category: AccountCategoryType.INCOME,
    subCategory: 'Other money inflow',
    priority: 27,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'neft trans',
    category: AccountCategoryType.INCOME,
    subCategory: 'Other money inflow',
    priority: 28,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'payment',
    category: AccountCategoryType.INCOME,
    subCategory: 'Other money inflow',
    priority: 29,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'inward transfer',
    category: AccountCategoryType.INCOME,
    subCategory: 'Other money inflow',
    priority: 30,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'inflow',
    category: AccountCategoryType.INCOME,
    subCategory: 'Other money inflow',
    priority: 31,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'deposit',
    category: AccountCategoryType.INCOME,
    subCategory: 'Other money inflow',
    priority: 32,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'settlement',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from sales',
    priority: 33,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'paystack',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from sales',
    priority: 34,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'flutterwave',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from sales',
    priority: 35,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'moniepoint',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from sales',
    priority: 36,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'opay',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from sales',
    priority: 37,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'palmpay',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from sales',
    priority: 38,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'pos',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from sales',
    priority: 39,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'salary',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Salaries & Wages',
    priority: 41,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'wages',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Salaries & Wages',
    priority: 42,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'rent',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Rent',
    priority: 43,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'airtime',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Airtime/Data Subscription',
    priority: 40,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'data subscription',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Airtime/Data Subscription',
    priority: 45,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'mtn',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Airtime/Data Subscription',
    priority: 51,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'airtel',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Airtime/Data Subscription',
    priority: 52,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'glo',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Airtime/Data Subscription',
    priority: 53,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: '9mobile',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Airtime/Data Subscription',
    priority: 54,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'spectranet',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Airtime/Data Subscription',
    priority: 55,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'smile',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Airtime/Data Subscription',
    priority: 56,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'internet',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Airtime/Data Subscription',
    priority: 50,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'ikeja electric',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Utlity Bill (Light, Water, Waste etc.)',
    priority: 60,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'electricity',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Utlity Bill (Light, Water, Waste etc.)',
    priority: 65,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'water bill',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Utlity Bill (Light, Water, Waste etc.)',
    priority: 70,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'eko electric',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Utlity Bill (Light, Water, Waste etc.)',
    priority: 71,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'aedc',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Utlity Bill (Light, Water, Waste etc.)',
    priority: 72,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'ibedc',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Utlity Bill (Light, Water, Waste etc.)',
    priority: 73,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'nepa',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Utlity Bill (Light, Water, Waste etc.)',
    priority: 74,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'phcn',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Utlity Bill (Light, Water, Waste etc.)',
    priority: 75,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'uber',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Transportation & Logistics',
    priority: 80,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'bolt',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Transportation & Logistics',
    priority: 85,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'fuel',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Transportation & Logistics',
    priority: 90,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'taxify',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Transportation & Logistics',
    priority: 91,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'logistics',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Transportation & Logistics',
    priority: 92,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'dispatch',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Transportation & Logistics',
    priority: 93,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'courier',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Transportation & Logistics',
    priority: 94,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'transfer from',
    category: AccountCategoryType.TRANSFER,
    subCategory: 'Transfer from other business account',
    priority: 100,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'mobile trf to',
    category: AccountCategoryType.TRANSFER,
    subCategory: 'Transfer to other business account',
    priority: 106,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'mobile trf from',
    category: AccountCategoryType.TRANSFER,
    subCategory: 'Transfer from other business account',
    priority: 107,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'trf to',
    category: AccountCategoryType.TRANSFER,
    subCategory: 'Transfer to other business account',
    priority: 108,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'trf from',
    category: AccountCategoryType.TRANSFER,
    subCategory: 'Transfer from other business account',
    priority: 109,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'transfer to',
    category: AccountCategoryType.TRANSFER,
    subCategory: 'Transfer to other business account',
    priority: 104,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'pos settlement',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from sales',
    priority: 110,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'sales',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from sales',
    priority: 115,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'brand deal',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from brand deal',
    priority: 116,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'creative gig',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from creative gigs',
    priority: 117,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'creative gigs',
    category: AccountCategoryType.INCOME,
    subCategory: 'Money from creative gigs',
    priority: 118,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'purchase',
    category: AccountCategoryType.COGS,
    subCategory: 'Goods Purchased',
    priority: 120,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'inventory',
    category: AccountCategoryType.COGS,
    subCategory: 'Goods Purchased',
    priority: 125,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'packaging',
    category: AccountCategoryType.COGS,
    subCategory: 'Packaging Cost',
    priority: 130,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'delivery',
    category: AccountCategoryType.COGS,
    subCategory: 'Distribution Cost',
    priority: 135,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'meta',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Marketing/Advertising',
    priority: 140,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'google ads',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Marketing/Advertising',
    priority: 145,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'subscription',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Subscription - Capcut, Captions etc.',
    priority: 150,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'professional service',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Professional Services',
    priority: 155,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'consulting',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Professional Services',
    priority: 156,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'legal fee',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Professional Services',
    priority: 157,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'audit fee',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Professional Services',
    priority: 158,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'insurance',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Insurance',
    priority: 159,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'aiico',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Insurance',
    priority: 160,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'office supplies',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Supplies & Stationery',
    priority: 161,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'stationery',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Supplies & Stationery',
    priority: 162,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'repairs',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Repairs & Maintenance',
    priority: 163,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'maintenance',
    category: AccountCategoryType.EXPENSE,
    subCategory: 'Repairs & Maintenance',
    priority: 164,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'personal withdrawal',
    category: AccountCategoryType.EQUITY,
    subCategory: 'Personal Use',
    priority: 166,
  },
  {
    matchType: MatchType.CONTAINS,
    matchValue: 'personal use',
    category: AccountCategoryType.EQUITY,
    subCategory: 'Personal Use',
    priority: 167,
  },
];

@Injectable()
export class CategorizationRulesSeed {
  private readonly logger = new Logger(CategorizationRulesSeed.name);

  constructor(
    @InjectRepository(CategorizationRule)
    private readonly ruleRepo: Repository<CategorizationRule>,
  ) {}

  async run() {
    this.logger.log('Seeding default categorization rules...');

    await this.ruleRepo.delete({
      isSystem: true,
      matchValue: In(['transfer from', 'transfer to']),
    });

    for (const ruleData of DEFAULT_CATEGORIZATION_RULES) {
      const existing = await this.ruleRepo.findOne({
        where: {
          isSystem: true,
          matchType: ruleData.matchType,
          matchValue: ruleData.matchValue,
          category: ruleData.category,
          subCategory: ruleData.subCategory,
        },
      });

      if (existing) continue;

      await this.ruleRepo.save(
        this.ruleRepo.create({
          ...ruleData,
          isSystem: true,
          isActive: true,
          businessId: null,
        }),
      );
    }
  }
}
